const Vini = [
  {
    nome: "vini bianchi",
    contenuto: [
      {
        nome: "J'abbruzzu",
        nomeMinuscolo: "Trebbiano",
        testo: "Podere Castorani",
        prezzo: "16,00",
      },
      {
        nome: "Amorino",
        nomeMinuscolo: "Trebbiano d'Abruzzo DOC Superiore",
        testo: "Podere Castorani",
        prezzo: "21,00",
      },
      {
        nome: "Amorino",
        nomeMinuscolo: "Abruzzo Pecorino DOC Superiore",
        testo: "Podere Castorani",
        prezzo: "21,00",
      },
      {
        nome: "Villa gemma",
        nomeMinuscolo: "Bianco Colline Teatine IGT",
        testo: "Masciarelli Tenute Agricole",
        prezzo: "23,00",
      },
      {
        nome: "Marina Cvetic",
        nomeMinuscolo: "Trebbiano d'Abruzzo DOC Riserva",
        testo: "Masciarelli Tenute Agricole",
        prezzo: "45,00",
      },
      {
        nome: "Malandrino",
        nomeMinuscolo: "Trebbiano d'Abruzzo DOC",
        testo: "Cataldi Madonna",
        prezzo: "23,00",
      },
      {
        nome: "Giulia",
        nomeMinuscolo: "Pecorino IGT Terre Aquilane",
        testo: "Cataldi Madonna",
        prezzo: "23,00",
      },
      {
        nome: "60 passi",
        nomeMinuscolo: "Pecorino Colline Pescaresi IGP",
        testo: "Cantina Marramiero",
        prezzo: "19,00",
      },
      {
        nome: "Emidio Pepe 2022",
        nomeMinuscolo: "Trebbiano d'Abruzzo DOC",
        testo: "Emidio Pepe",
        prezzo: "60,00",
      },
      {
        nome: "emidio pepe 2022",
        nomeMinuscolo: "Pecorino Colli Aprutini IGT 2022",
        testo: "Emidio Pepe",
        prezzo: "80,00",
      },
      {
        nome: "Cococciola",
        nomeMinuscolo: "Terre di Chieti IGP",
        testo: "Tenuta Ulisse",
        prezzo: "23,00",
      },
      {
        nome: "Passerina",
        nomeMinuscolo: "Terre di Chieti IGP",
        testo: "Tenuta Ulisse",
        prezzo: "23,00",
      },
      {
        nome: "Trebbiano Bossanova",
        nomeMinuscolo: "Trebbiano D'Abruzzo Bossanova",
        testo: "Cantina Bossanova",
        prezzo: "35,00",
      },
      {
        nome: "Il Pecorino",
        nomeMinuscolo: "Il Pecorino",
        testo: "San Lorenzo",
        prezzo: "20,00",
      },
      {
        nome: "Bianco Limited Edition",
        nomeMinuscolo: "EDIZIONE BIANCO 99 PUNTI Limited Edition",
        testo: "Fantini",
        prezzo: "50,00",
      },
      {
        nome: "chardonnay",
        nomeMinuscolo: "Alto Adige DOC",
        testo: "Kellerei Meran Burggräfler",
        prezzo: "18,00",
      },
      {
        nome: "Gewurztraminer",
        nomeMinuscolo: "Alto Adige DOC",
        testo: "Kellerei Meran Burggräfler",
        prezzo: "25,00",
      },
      {
        nome: "Mezzopieno",
        nomeMinuscolo: "Mezzopieno",
        testo: "Azienda Agricola Massetti Francesco",
        prezzo: "35,00",
      },      
      {
        nome: "Pecorino Fantini Mithus",
        nomeMinuscolo: "MITHUS PECORINO TERRE DI CHIETI IGT",
        testo: "Fantini",
        prezzo: "21,00",
      },
      {
        nome: "Pecorino Fantini Calalenta",
        nomeMinuscolo: "CALALENTA PECORINO TERRE DI CHIETI IGT",
        testo: "Fantini",
        prezzo: "21,00",
      },
     {
        nome: "Vermentino di Sardegna Cala Reale",
        nomeMinuscolo: "Vermentino di Sardegna Cala Reale",
        testo: "Sella & Mosca",
        prezzo: "21,00",
      },
     {
        nome: "PET-NAT Vino Ancestrale",
        nomeMinuscolo: "PET-NAT Vino Ancestrale Malvasia Colline Pescaresi IGT",
        testo: "Podere Castorani",
        prezzo: "20,00",
      },
     ],
  },
  {
    nome: "vini rossi",
    contenuto: [
      {
        nome: "malandrino",
        nomeMinuscolo: "Montepulciano d'Abruzzo bio",
        testo: "Cataldi Madonna",
        prezzo: "23,00",
      },
      {
        nome: "testa rossa rosso",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC",
        testo: "Pasetti",
        prezzo: "28,00",
      },
      {
        nome: "J'abbruzzu",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC",
        testo: "Podere Castorani",
        prezzo: "16,00",
      },
      {
        nome: "Amorino",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC",
        testo: "Podere Castorani",
        prezzo: "21,00",
      },
      {
        nome: "Inferi",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC Riserva 2019",
        testo: "Marramiero",
        prezzo: "30,00",
      },
      {
        nome: "San Leone",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOP",
        testo: "Fuschi",
        prezzo: "26,00",
      },
      {
        nome: "Antàres",
        nomeMinuscolo: "Montepulciano d'Abruzzo Colline Teramane DOCG",
        testo: "San Lorenzo Vini",
        prezzo: "18,00",
      },
      {
        nome: "emidio pepe 2020",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC",
        testo: "Emidio Pepe",
        prezzo: "65,00",
      },
      {
        nome: "Marina Cvetic",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC Riserva",
        testo: "Masciarelli Tenute Agricole",
        prezzo: "35,00",
      },
      {
        nome: "villa gemma 2017",
        nomeMinuscolo: "Montepulciano d'Abruzzo DOC Riserva",
        testo: "Masciarelli Tenute Agricole",
        prezzo: "70,00",
      },
      {
        nome: "Montepulciano D'Abruzzo Bossanova",
        nomeMinuscolo: "Montepulciano D'Abruzzo Bossanova",
        testo: "Cantina Bossanova",
        prezzo: "45,00",
      },
      {
        nome: "Quarantacinquè",
        nomeMinuscolo: "Quarantacinquè Montepulciano D'Abruzzo Doc",
        testo: "Azienda Agricola Massetti Francesco",
        prezzo: "45,00",
      },
    ],
  },
  {
    nome: "vini rosati",
    contenuto: [
      {
        nome: "rosato san lorenzo",
        nomeMinuscolo: "Colli Aprutini IGT",
        testo: "San Lorenzo Vini",
        prezzo: "19,00",
      },
      {
        nome: "villa gemma",
        nomeMinuscolo: "Cerasuolo d'Abruzzo DOC",
        testo: "Masciarelli Tenute Agricole",
        prezzo: "23,00",
      },
      {
        nome: "testa rossa rosato",
        nomeMinuscolo: "Terre Aquilane IGP",
        testo: "Pasetti",
        prezzo: "21,00",
      },
      {
        nome: "J'abbruzzu",
        nomeMinuscolo: "Cerasuolo d'Abruzzo DOC",
        testo: "Podere Castorani",
        prezzo: "16,00",
      },
      {
        nome: "Amorino",
        nomeMinuscolo: "Cerasuolo d'Abruzzo DOC",
        testo: "Podere Castorani",
        prezzo: "21,00",
      },
      {
        nome: "Tatì",
        nomeMinuscolo: "Cerasuolo d'Abruzzo Dop",
        testo: "Cantina Fuschi",
        prezzo: "21,00",
      },
      {
        nome: "merlot",
        nomeMinuscolo: "Terre di Chieti IGT",
        testo: "Tenute Ulisse",
        prezzo: "23,00",
      },
      {
        nome: "malandrino",
        nomeMinuscolo: "Cerasuolo d'Abruzzo bio DOC",
        testo: "Cataldi Madonna",
        prezzo: "21,00",
      },
      {
        nome: "calalenta",
        nomeMinuscolo: "Merlot Rosato",
        testo: "Cantina Fantini",
        prezzo: "21,00",
      },
     {
        nome: "cerasuolo bossanova",
        nomeMinuscolo: "Cerasuolo D'Abruzzo Bossanova",
        testo: "Cantina Bossanova",
        prezzo: "35,00",
      },
      {
        nome: "rosato igt colli aprutini",
        nomeMinuscolo: "C'è Rosato IGT Colli Aprutini",
        testo: "Azienda Agricola Massetti Francesco",
        prezzo: "35,00",
      },
      {
        nome: "cerasuolo emidio pepe",
        nomeMinuscolo: "Cerasiolo D'Abruzzo 2022",
        testo: "Emidio Pepe",
        prezzo: "60,00",
      },
      {
        nome: "mithus",
        nomeMinuscolo: "Mithus Merlot",
        testo: "Fantini",
        prezzo: "21,00",
      },
    ],
  },
  {
    nome: "spumanti & champagne",
    contenuto: [
      {
        nome: "pecorino brut",
        testo: "San Lorenzo Vini",
        prezzo: "18,00",
      },
      {
        nome: "rosato brut",
        testo: "San Lorenzo Vini",
        prezzo: "20,00",
      },
      {
        nome: "za grazia",
        nomeMinuscolo: "Za' Grazia",
        testo: "Cantina Fuschi",
        prezzo: "18,00",
      },
      {
        nome: "Fuschi Rosa",
        nomeMinuscolo: "Fuschi Rosa",
        testo: "Cantina Fuschi",
        prezzo: "18,00",
      },
      {
        nome: "passerina podere castorani",
        nomeMinuscolo: "Metodo Classico Millesimato",
        testo: "Podere Castorani",
        prezzo: "36,00",
      },
      {
        nome: "gran cuvée bianca",
        nomeMinuscolo: "Swarovsky",
        testo: "Cantina Fantini",
        prezzo: "21,00",
      },
      {
        nome: "gran cuvée rosé",
        nomeMinuscolo: "Swarovsky",
        testo: "Cantina Fantini",
        prezzo: "21,00",
      },
      {
        nome: "ferrari brut",
        testo: "Ferrari - Fratelli Lunelli",
        prezzo: "33,00",
      },
      {
        nome: "cuvée imperiale brut",
        nomeMinuscolo: "Franciacorta",
        testo: "Guido Berlucchi & C.",
        prezzo: "33,00",
      },
      {
        nome: "yellow label",
        nomeMinuscolo: "Champagne Brut",
        testo: "Veuve Clicquot & Ponsardin",
        prezzo: "65,00",
      },
      {
        nome: "fernand lemarie",
        nomeMinuscolo: "FERNAND LEMAIRE Champagne Brut",
        testo: "Fernand Lemarie",
        prezzo: "50,00",
      },
      {
        nome: "theophile",
        nomeMinuscolo: "Thèophile Champagne Brut",
        testo: "Louis Roederer",
        prezzo: "50,00",
      },
      {
        nome: "demonge",
        nomeMinuscolo: "Demonge Champagne Brut-Rosè",
        testo: "Demonge",
        prezzo: "55,00",
      },
      {
        nome: "leon launois",
        nomeMinuscolo: "LEON LAUNOIS Champagne Cuvée Rèservèe Brut",
        testo: "Azienda Vinicola Léon Launois",
        prezzo: "50,00",
      },

      {
        nome: "princes blanc de blancs",
        nomeMinuscolo: "Princes Blanc De Blancs Brut",
        testo: "De Venoge",
        prezzo: "95,00",
      },

      {
        nome: "princes blanc de noirs",
        nomeMinuscolo: "Princes Blanc De Noirs Brut",
        testo: "De Venoge",
        prezzo: "105,00",
      },
      {
        nome: "princes extra brut",
        nomeMinuscolo: "Princes Extra Brut",
        testo: "De Venoge",
        prezzo: "95,00",
      },
      
      {
        nome: "princes rosè brut",
        nomeMinuscolo: "Princes Rosè Brut",
        testo: "De Venoge",
        prezzo: "110,00",
      },
    ],
  },
];

export default Vini;
